#!/bin/bash

echo -n "$GC_SA" | base64 -d > credentials.json

cat << EOF > .env
DISCORD_TOKEN=$DISCORD_TOKEN
DISCORD_EVENTS_ID=$DISCORD_EVENTS_ID
DISCORD_GUILD_ID=$DISCORD_GUILD_ID
DISCORD_ROLE_ID=$DISCORD_ROLE_ID
DISCORD_ROLE_TTP_ID=$DISCORD_ROLE_TTP_ID
DISCORD_ROLE_TECHTONICA_ID=$DISCORD_ROLE_TECHTONICA_ID
GCAL_ID=$GCAL_ID
EOF

